<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="c-block <?= $block->escapeHtmlAttr($block->getBlockCss()) ?>">
    <div class="c-block__title <?= $block->escapeHtmlAttr($block->getBlockCss()) ?>-title">
        <strong><?= $block->escapeHtml($block->getBlockTitle()) ?></strong>
    </div>
    <div class="c-block__content <?= $block->escapeHtmlAttr($block->getBlockCss()) ?>-content">
        <?= $block->getChildHtml() ?>
    </div>
</div>
