<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php if ($crumbs && is_array($crumbs)) : ?>
<div class="c-breadcrumbs c-breadcrumbs--theme">
    <ul class="c-breadcrumbs__list o-list-inline">
        <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
            <li class="c-breadcrumbs__item c-breadcrumbs__item--<?= $block->escapeHtmlAttr($crumbName) ?> o-list-inline__item">
            <?php if ($crumbInfo['link']) : ?>
                <a href="<?= $block->escapeUrl($crumbInfo['link']) ?>"
                   title="<?= $block->escapeHtmlAttr($crumbInfo['title']) ?>">
                    <?= $block->escapeHtml($crumbInfo['label']) ?>
                </a>
            <?php elseif ($crumbInfo['last']) : ?>
                <strong><?= $block->escapeHtml($crumbInfo['label']) ?></strong>
            <?php else : ?>
                <?= $block->escapeHtml($crumbInfo['label']) ?>
            <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
