<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<div class="c-toolbar__amount o-flex__item u-1/2" id="toolbar-amount">
    <?php if ($block->getLastPageNum() > 1) :?>
        <?= $block->escapeHtml(
            __(
                'Items %1-%2 of %3',
                $block->getFirstNum(),
                $block->getLastNum(),
                $block->getTotalNum()
            )
        ) ?>
    <?php elseif ($block->getTotalNum() == 1) :?>
        <?= $block->escapeHtml(
            __('%1 Item', $block->getTotalNum()),
            ['span']
        ) ?>
    <?php else :?>
        <?= $block->escapeHtml(
            __('%1 Items', $block->getTotalNum()),
            ['span']
        ) ?>
    <?php endif; ?>
</div>
