<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<div class="c-limiter o-flex__item u-1/2">
    <label class="label" for="limiter">
        <?= $block->escapeHtml(__('Show')) ?>
    </label>
    <div class="c-limiter__control">
        <select id="limiter" data-role="limiter" class="c-limiter__options">
            <?php foreach ($block->getAvailableLimit() as $_key => $_limit) :?>
                <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                    <?php if ($block->isLimitCurrent($_key)) :?>
                        selected="selected"
                    <?php endif ?>>
                    <?= $block->escapeHtml($_limit) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
    <span class="c-limiter__text"><?= $block->escapeHtml(__('per page')) ?></span>
</div>
