<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<?php if ($block->isEnabledViewSwitcher()) :?>
    <div class="c-modes o-flex__item u-1/2">
        <?php $_modes = $block->getModes(); ?>
        <?php if ($_modes && count($_modes) > 1) :?>
            <strong class="c-modes__label" id="modes-label"><?= $block->escapeHtml(__('View as')) ?></strong>
            <?php foreach ($block->getModes() as $_code => $_label) :?>
                <?php if ($block->isModeActive($_code)) :?>
                    <strong title="<?= $block->escapeHtmlAttr($_label) ?>"
                            class="c-modes__mode c-modes__mode--active c-modes__mode--<?= $block->escapeHtmlAttr(strtolower($_code)) ?>"
                            data-value="<?= $block->escapeHtmlAttr(strtolower($_code)) ?>">
                        <span><?= $block->escapeHtml($_label) ?></span>
                    </strong>
                <?php else :?>
                    <a class="c-modes__mode c-modes__mode--<?= $block->escapeHtmlAttr(strtolower($_code)) ?>"
                       title="<?= $block->escapeHtmlAttr($_label) ?>"
                       href="#"
                       data-role="mode-switcher"
                       data-value="<?= $block->escapeHtmlAttr(strtolower($_code)) ?>"
                       id="mode-<?= $block->escapeHtmlAttr(strtolower($_code)) ?>"
                       aria-labelledby="modes-label mode-<?= $block->escapeHtmlAttr(strtolower($_code)) ?>">
                        <span><?= $block->escapeHtml($_label) ?></span>
                    </a>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
<?php endif; ?>
